name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      APP_URL: "http://127.0.0.1:8000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Prepare The Environment
        run: cp .env.example .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction
        
      - name: Generate Application Key
        run: php artisan key:generate

      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --detect

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php artisan serve --no-reload &

      - name: Run Dusk Tests
        run: php artisan dusk
